#tomcat端口配置
server:
  port: 8082

#日志配置
logging:
  level: 
    learning: trace

spring:
  #mongodb配置
  data:
    mongodb:
      host: 192.168.1.111
      port: 27017
      database: test
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.188:3306/HospitalDevice
    username: hd-dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  #模板引擎
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/template
    suffix: .html
    prefix: /html/
  #redis缓存配置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 10
      max-wait: 10
      min-idle: 1
      max-idle: 1

#mybatis配置：实体类路径+sql文件mapper
mybatis:
  type-aliases-package: cn.smarthse.core.model
  mapper-locations: classpath:mapper/**/*Mapper.xml

#邮件配置
mail:
  host: smtp.163.com
  port: 21  
  username: darcy_lee@163.com #开通了smtp服务的QQ邮箱  
  password: darcy002674 #授权码  
  smtp:
    auth: true  
    timeout: 30000  
    starttls.enable: true
    socketFactory.port: 
  from: darcy_lee@163.com
  replyTo: 306623095@qq.com  

    
